version: '3.8'

services:
  tapo-mqtt-bridge:
    build: '.'
    environment:
      TP_LINK_EMAIL: ${TP_LINK_EMAIL}
      TP_LINK_PASSWORD: ${TP_LINK_PASSWORD}
      MQTT_BROKER_ADDRESS: ${MQTT_BROKER_ADDRESS:-localhost}
      MQTT_BROKER_PORT: ${MQTT_BROKER_PORT:-1883}
    volumes:
      - ./devices.yml:/etc/tapo-mqtt-bridge/devices.yml:ro
    restart: unless-stopped
